home:
  path: '/'
  controller: 'App\Controllers\DefaultController::default'

users:
  path: '/users'
  require: 'routes/users'

custom:
  path: '/custom/[string]'
  controller: 'App\Controllers\DefaultController::custom'
  params:
    string
