security:
  firewall:
    type: 'public'
    entity:
      class: 'App\Entity\Users'
      login: 'email'
      password: 'password'
    token:
      encode: 'sha256'
      secret: 'secretKey'
    anonymous:
      home
      users_list
